# Generated by Django 4.2.4 on 2024-05-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empprof',
            old_name='uername',
            new_name='username',
        ),
    ]
