# Generated by Django 4.2.4 on 2024-05-30 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0002_rename_uername_empprof_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empprof',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='empprof',
            old_name='username',
            new_name='username1',
        ),
    ]
