# Generated by Django 4.2.4 on 2024-05-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0003_rename_password_empprof_password1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerProf',
            fields=[
                ('username1', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password1', models.CharField(max_length=20)),
            ],
        ),
    ]
