# Generated by Django 4.2.4 on 2024-05-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0004_managerprof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerprof',
            old_name='password1',
            new_name='password2',
        ),
        migrations.RenameField(
            model_name='managerprof',
            old_name='username1',
            new_name='username2',
        ),
    ]
