# Generated by Django 4.2.4 on 2024-06-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0005_rename_password1_managerprof_password2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=100)),
                ('telephone1', models.CharField(max_length=15)),
                ('gender1', models.CharField(max_length=10)),
                ('employmentType', models.CharField(max_length=15)),
                ('salary1', models.CharField(max_length=15)),
                ('date1', models.DateField()),
            ],
        ),
    ]
