# Generated by Django 4.2.4 on 2024-06-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0006_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='address1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date1',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employmentType',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='gender1',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name1',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary1',
            new_name='salary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='telephone1',
            new_name='telephone',
        ),
    ]
