# Generated by Django 4.2.4 on 2024-06-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0007_rename_address1_employee_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
