# Generated by Django 4.2.4 on 2024-06-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0008_remove_employee_id_alter_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('startDate', models.DateField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=255)),
                ('endDate', models.DateField()),
                ('totalDays', models.IntegerField()),
                ('reason', models.TextField()),
                ('medicalCertificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/')),
            ],
        ),
    ]
