# Generated by Django 4.2.4 on 2024-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0009_leaveapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='medicalCertificate',
            field=models.ImageField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
    ]
