# Generated by Django 4.2.4 on 2024-06-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0010_alter_leaveapplication_medicalcertificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='medicalCertificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
    ]
