# Generated by Django 4.2.4 on 2024-06-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdjango', '0012_alter_leaveapplication_medicalcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
